### ISSUE TITLE
[Bug] API isn't written in NodeJS

### ISSUE THREAD

**Issue by haydennyyy** [gtsatsis/RLAPI-v3-OOP#149]
**Describe the bug**
The API is written in a terrible API language, should be written in nOdEjS

**To Reproduce**
1. Use the API at all, or acknowledge its existence

**Expected behavior**
I expected the API to work well, but it's written in PHP?

**Screenshots**
https://php.net

**Additional context**
#3 would be fixed easier by using Node...

**Comment by gtsatsis** [comment]
No. I'd honestly rather write it in Golang (ahem, @JakeMakesStuff), or even Ruby.

**Comment by haydennyyy** [comment]
But... But... TypeScript

**Comment by haydennyyy** [comment]
Tell you what, we'll make a compromise.

C# & .NET

**Comment by gtsatsis** [comment]
No is no. Consent was not given. Any action taken will be illega- oh wait this isn't sexual intercourse..

Uh, no. I hate JS.

**Comment by haydennyyy** [comment]
Goddamn, did GNU/Jake touch you too?

**Comment by gtsatsis** [comment]
Y-yes..

**Comment by DaRealJeffwey** [comment]
it isn't made in batch (not bash)
