### ISSUE TITLE
Code design flaw

### ISSUE THREAD

**Issue by samueldcs** [gtsatsis/RLAPI-v3-OOP#3]
https://github.com/gtsatsis/RLAPI-v3-OOP/blob/b873773ed6df49773330c519bb35fb5f71cd3bb1/src/Uploader.php#L11

You are not supposed to access the request body directly from the class, instead, pass the value from the API endpoint (index.php).

Example (index.php):
```php
if(isset($_GET['bucket'] && !is_null[$_GET['bucket'])) {
    $uploader = new RLME\Uploader($_GET['bucket']);
}
````
And if the bucket is not set (`isset() == false`), set a default value on the constructor.

Example (Uploader.php)
```php
function __construct($bucket = 'owoapi') {}
````

If you want, I can create a PR solving this issue

**Comment by gtsatsis** [comment]
We're currently not working on the uploader, and that's just bootstrap code.

If you want to make a PR, you could, but if not, it'll be fixed when we start work on the uploader

**Comment by samueldcs** [comment]
Just keep that in mind and fix it when you can.
